seed: 42
pgnn:
  momentum: 0
  sgd_lr: 0.001
  num_splits: 1
  num_epochs: 500
  adam_lr: 0.0001
  dropout_rate: 0.2
  weight_decay: 0.0001
  test_batch_size: 128
  train_batch_size: 512
kpnn:
  a: 3
gnn:
  a: 3
ann:
  a: 3