seed: 42
TPM: True
minmax: False
val_size: 0.2
test_size: 0.2  
sma_window: 10
batch_size: 256
num_epochs: 500

ann:
  alpha: 0.001
gnn:
  num_heads: 2
  alpha: 0.001
  dropout_rate: 0
  hidden_channels: 16
megagnn:
  num_heads: 2
  alpha: 0.001
  dropout_rate: 0
  hidden_channels: 16
pgnn:
  alpha: 0.001
  dropout_rate: 0
  weight_decay: 0.0001
kpnn:
  alpha: 0.001
  lambda_: 0.2
  node_dropout: 0
  gene_dropout: 0
  num_grad_epsilon: 0.001
  optimizer: AdamOptimizer