seed: 42
TPM: True
minmax: False
val_size: 0.2
test_size: 0.2  
batch_size: 512
num_epochs: 1500

ann:
  a: 3
gnn:
  a: 3
pgnn:
  momentum: 0
  sgd_lr: 0.001
  adam_lr: 0.0001
  dropout_rate: 0.2
  weight_decay: 0.0001
kpnn:
  a: 3