seed: 42
TPM: True
minmax: False
val_size: 0.2
test_size: 0.2  
sma_window: 10
batch_size: 512
num_epochs: 1500

ann:
  alpha: 0.001
gnn:
  alpha: 0.001
pgnn:
  momentum: 0
  sgd_alpha: 0.001
  adam_alpha: 0.0001
  dropout_rate: 0.2
  weight_decay: 0.0001
  num_pathways: 323
  num_drug_genes: 741
  num_cellline_genes: 537
kpnn:
  alpha: 0.001
  lambda_: 0.2
  node_dropout: 0
  gene_dropout: 0
  num_grad_epsilon: 0.001
  optimizer: AdamOptimizer